# Stage 1: Dependencies
FROM node:22-bullseye AS deps
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y curl wget openssl && rm -rf /var/lib/apt/lists/*

# Install project dependencies
COPY package.json package-lock.json ./
COPY prisma ./prisma/
RUN npm ci --legacy-peer-deps
RUN npx prisma generate

# Stage 2: Builder
FROM node:22-bullseye AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Set build-time environment variables
ARG MENTOR_API_URL
ARG WP_USER
ARG WP_PASSWORD
ARG NEXT_PUBLIC_SITE_URL
ARG RAZORPAY_KEY_ID
ARG RAZORPAY_KEY_SECRET
ARG RAZORPAY_WEBHOOK_SECRET
ARG WP_PAYMENT_API_BASE_URL
ARG WP_INTERNAL_URL
ARG LEAD_WEBHOOK_SECRET
ARG NANOSCHOOL_WEBHOOK_SECRET
ARG USER_FEEDBACK_API
ARG INTERNSHIP_API_URL
ARG UPCOMING_EVENTS_API_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG ADMIN_EMAILS
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG DATABASE_URL
ARG ADMIN_PASSWORD
ARG GEMINI_API_KEY
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG AWS_SES_FROM_ADDRESS

ENV MENTOR_API_URL=$MENTOR_API_URL
ENV WP_USER=$WP_USER
ENV WP_PASSWORD=$WP_PASSWORD
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV RAZORPAY_KEY_ID=$RAZORPAY_KEY_ID
ENV RAZORPAY_KEY_SECRET=$RAZORPAY_KEY_SECRET
ENV RAZORPAY_WEBHOOK_SECRET=$RAZORPAY_WEBHOOK_SECRET
ENV WP_PAYMENT_API_BASE_URL=$WP_PAYMENT_API_BASE_URL
ENV WP_INTERNAL_URL=$WP_INTERNAL_URL
ENV LEAD_WEBHOOK_SECRET=$LEAD_WEBHOOK_SECRET
ENV NANOSCHOOL_WEBHOOK_SECRET=$NANOSCHOOL_WEBHOOK_SECRET
ENV USER_FEEDBACK_API=$USER_FEEDBACK_API
ENV INTERNSHIP_API_URL=$INTERNSHIP_API_URL
ENV UPCOMING_EVENTS_API_URL=$UPCOMING_EVENTS_API_URL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV ADMIN_EMAILS=$ADMIN_EMAILS
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV DATABASE_URL=$DATABASE_URL
ENV ADMIN_PASSWORD=$ADMIN_PASSWORD
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_REGION=$AWS_REGION
ENV AWS_SES_FROM_ADDRESS=$AWS_SES_FROM_ADDRESS

# Disable Next.js telemetry during build
ENV NEXT_TELEMETRY_DISABLED 1

RUN npm run build

# Stage 3: Runner
FROM node:22-bullseye AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

# Create non-privileged user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy standalone output and static files
COPY --from=builder /app/public ./public
COPY --from=builder /app/prisma ./prisma
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["node", "server.js"]
